// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Call as $Call, Create as $Create} from "@wailsio/runtime";

/**
 * @returns {Promise<void> & { cancel(): void }}
 */
export function Exit() {
    let $resultPromise = /** @type {any} */($Call.ByID(1640504044));
    return $resultPromise;
}

/**
 * @param {string} name
 * @returns {Promise<string> & { cancel(): void }}
 */
export function Greet(name) {
    let $resultPromise = /** @type {any} */($Call.ByID(1411160069, name));
    return $resultPromise;
}

/**
 * @returns {Promise<boolean> & { cancel(): void }}
 */
export function IsAdmin() {
    let $resultPromise = /** @type {any} */($Call.ByID(3232019819));
    return $resultPromise;
}
